use crate::error::Error;
use crate::project::manifest::Environment;
use crate::registry::index::DownloadSource;
use serde::{Deserialize, Serialize};
use std::path::Path;

pub const LOCKFILE: &str = "lpm.lock";

/// exactly what `lpm install` resolved, so `--locked` can replay it without touching any index.
#[derive(Serialize, Deserialize, Debug)]
pub struct Lockfile {
    pub version: u32,
    #[serde(default, rename = "package")]
    pub packages: Vec<LockedPackage>,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    /// the package's own environment. names the nested-link folder
    /// dependents require it through.
    pub environment: Environment,
    /** which environment root the package installs under, the root of the
    dependency tree that pulled it in. absent when it equals `environment`,
    also absent in pre-v2 lockfiles which knew no such distinction. read it
    through [`LockedPackage::context`]. */
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context: Option<Environment>,
    /// top-level link file name, absent for transitives which get none.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    pub index: String,
    /** this package's [overrides]-rewritten edges, declared alias -> the
    replacement's package name. additive, locks without it parse fine,
    and `--locked` needs it to relink redirected dependencies. */
    #[serde(default, skip_serializing_if = "std::collections::BTreeMap::is_empty")]
    pub redirects: std::collections::BTreeMap<String, String>,
    /** the patch this copy was built with, when [patches] named it.
    additive within v2 like `redirects`. `--locked` replays it straight
    from here without consulting the manifest. */
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub patch: Option<PatchRecord>,
    #[serde(flatten)]
    pub source: DownloadSource,
}

/** a patch as the lockfile remembers it, the repo-relative file plus a
hex FNV-1a of its bytes, so an edited patch reads as a change even when
every version resolved identically. */
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct PatchRecord {
    pub path: String,
    pub hash: String,
}

impl PatchRecord {
    pub fn new(path: String, bytes: &[u8]) -> Self {
        PatchRecord {
            path,
            hash: format!("{:016x}", crate::sys::hash::fnv1a(bytes)),
        }
    }

    /// whether `bytes` are the bytes this record was made from.
    pub fn matches(&self, bytes: &[u8]) -> bool {
        self.hash == format!("{:016x}", crate::sys::hash::fnv1a(bytes))
    }
}

impl LockedPackage {
    /// the environment root this package installs under.
    pub fn context(&self) -> Environment {
        self.context.unwrap_or(self.environment)
    }
}

impl Lockfile {
    pub fn new(packages: Vec<LockedPackage>) -> Self {
        Lockfile {
            /* in v2 `link` went optional, absent on transitives, and `context`
            arrived. older lpm can't parse v2 locks. v1 locks load fine. */
            version: 2,
            packages,
        }
    }

    pub fn load() -> Result<Self, Error> {
        let path = Path::new(LOCKFILE);
        if !path.exists() {
            return Err(Error::LockfileMissing);
        }
        Ok(toml::from_str(&std::fs::read_to_string(path)?)?)
    }

    pub fn save(&self) -> Result<(), Error> {
        let header = "# This file is generated by `lpm install`; do not edit it manually.\n";
        let body = toml::to_string(self).expect("lockfile serializes");
        std::fs::write(LOCKFILE, format!("{header}{body}"))?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips() {
        let lockfile = Lockfile::new(vec![
            LockedPackage {
                name: "evaera/promise".to_string(),
                version: "4.0.0".to_string(),
                environment: Environment::Shared,
                // a shared package pulled in under a server root
                context: Some(Environment::Server),
                link: Some("Promise".to_string()),
                index: "https://github.com/UpliftGames/wally-index".to_string(),
                redirects: [("Signal".to_string(), "acme/signal-fork".to_string())].into(),
                patch: Some(PatchRecord::new(
                    "patches/evaera_promise@4.0.0.patch".to_string(),
                    b"--- a/init.lua\n+++ b/init.lua\n",
                )),
                source: DownloadSource::Zip {
                    url: "https://api.wally.run/v1/package-contents/evaera/promise/4.0.0"
                        .to_string(),
                },
            },
            LockedPackage {
                name: "pesde/hello".to_string(),
                version: "1.0.2".to_string(),
                environment: Environment::Luau,
                // a transitive in its own environment, no link, no context
                context: None,
                link: None,
                index: "https://github.com/pesde-pkg/index".to_string(),
                redirects: Default::default(),
                patch: None,
                source: DownloadSource::TarGz {
                    url: "https://registry.pesde.daimond113.com/v1/packages/pesde%2Fhello/1.0.2/luau/archive".to_string(),
                },
            },
        ]);

        let text = toml::to_string(&lockfile).unwrap();
        let parsed: Lockfile = toml::from_str(&text).unwrap();
        assert_eq!(parsed.version, 2);
        assert_eq!(parsed.packages.len(), 2);
        assert_eq!(parsed.packages[0].name, "evaera/promise");
        // redirects round-trip when present and stay absent otherwise
        assert_eq!(
            parsed.packages[0]
                .redirects
                .get("Signal")
                .map(String::as_str),
            Some("acme/signal-fork")
        );
        assert!(parsed.packages[1].redirects.is_empty());
        assert_eq!(text.matches("redirects").count(), 1);

        /* the patch record round-trips where present, stays absent
        otherwise, and an edited patch stops matching */
        let record = parsed.packages[0].patch.as_ref().unwrap();
        assert_eq!(record.path, "patches/evaera_promise@4.0.0.patch");
        assert!(record.matches(b"--- a/init.lua\n+++ b/init.lua\n"));
        assert!(!record.matches(b"something else"));
        assert!(parsed.packages[1].patch.is_none());
        assert_eq!(text.matches("[package.patch]").count(), 1);
        assert!(matches!(
            &parsed.packages[1].source,
            DownloadSource::TarGz { url } if url.contains("pesde%2Fhello")
        ));

        // context and link round-trip, absent fields staying absent
        assert_eq!(parsed.packages[0].context(), Environment::Server);
        assert_eq!(parsed.packages[0].link.as_deref(), Some("Promise"));
        assert_eq!(parsed.packages[1].context(), Environment::Luau);
        assert_eq!(parsed.packages[1].link, None);
        assert_eq!(text.matches("context").count(), 1);
        assert_eq!(text.matches("link").count(), 1);
    }

    #[test]
    fn v1_lockfiles_still_load() {
        /* the pre-context format, version 1, `link` on every entry, no
        `context` anywhere. context() falls back to the environment. */
        let parsed: Lockfile = toml::from_str(
            "version = 1\n\n\
             [[package]]\n\
             name = \"acme/thing\"\n\
             version = \"1.0.0\"\n\
             environment = \"shared\"\n\
             link = \"thing\"\n\
             index = \"https://example.com/index\"\n\
             type = \"zip\"\n\
             url = \"https://example.com/thing/1.0.0\"\n",
        )
        .unwrap();
        assert_eq!(parsed.version, 1);
        assert_eq!(parsed.packages[0].link.as_deref(), Some("thing"));
        assert_eq!(parsed.packages[0].context(), Environment::Shared);
    }
}
